config/routes.rb
Rails.application.routes.draw do

  root 'welcome#home'

  resources :users, only:[:new, :create, :show, :edit, :update] do
    resources :games
  end

  resources :rankings, only:[:new]

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'

  get '/logout' => 'sessions#destroy'

  get '/auth/:provider/callback' => 'sessions#create'

  get "/score" => "games#score"

  get "/logged_in_home" => "users#logged_in_home" 



end

app/models/application_controller.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :rankings
  has_many :users, through: :rankings
  validates :name, presence: true
  validates :play_time, numericality: true
  accepts_nested_attributes_for :rankings

  scope :pro_level, ->(play_time) { where("play_time > 200", play_time ) }

  scope :score, -> { where("score > 2500")}

  def rank_symbol(score)
    game = self.score
      if game >= 2500
        "You are a platinum rank CONGRATS!"
      elsif 2000 < game && game < 2499
        "You are a gold rank!"
      elsif 1500 < game && game < 1999
        "You are a silver rank"
      elsif 1000 < game && game < 1499
        "you are a bronze rank"
      else
        "you are a bronze rank :( keep trying!"
      end
  end
end

app/models/ranking.rb
class Ranking < ApplicationRecord
  belongs_to :user
  belongs_to :game

  def new_ranking(new_score)
    user = self.user
    game = self.game
      if game.score > new_score 
        game.score - new_score = total_score
        "Your new ranking is #{total_score}"
      elsif
         game.score < new_score
          new_score - game.score = total_score
          "Your new ranking is #{total_score}"
        else
          "Ranking has not changed!"
      end
    end


end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :rankings
  has_many :games, through: :rankings
  validates :name, presence: true
  validates :password_digest, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in
    current_user != nil
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def new
    @user = User.find(session[:user_id])
    @game = Game.new
    @ranking = @game.rankings.build
    #render "games/_form", :layout => false
  end

  def create
    @user = current_user
    @game = current_user.games.new(game_params)
      if @game.save
        respond_to do |f|
          f.json {render :layout => false, :json => @game}
          f.html {redirect_to user_path(@user)}
        end
      else
        render :new
      end
  end

  def index
    @games = current_user.games
    respond_to do |f|
      f.html {render :index}
      f.json {render :json => @games}
    end
  end

  def show
    @game = find_game
    @rank= Ranking.find_by(game_id: find_game)
    respond_to do |f|
      f.html {render :show}
      f.json {render :json => @game}
    end
  end

  def edit
    @user = current_user
    @game = find_game
  end

  def update
    @game = find_game
      if @game.update(game_params)
        respond_to do |f|
          f.json {render :json => @game}
          f.html {redirect_to user_game_path(@game)}
      end
      else
        render :edit
      end
  end

  def destroy
    @user = current_user
    @game = find_game
    @game.rankings.clear
    @game.delete
    redirect_to "/logged_in_home"
  end

  def score
    if :score
      @score = Game.score
      render "/games/score"
    else
      redirect_to user_games_path(current_user)
    end
  end

  private

  def game_params
    params.require(:game).permit(:name, :game_type, :play_time, :main_setup, :score, rankings_attributes: [:comment, :user_id])
  end

  def rank_comment
  end


  def find_game
      Game.find(params[:id])
    end
end

app/controllers/rankings_controller.rb
class RankingsController < ApplicationController

  def new #build out a new form with a new_score tag, i think thatll work..
    @ranking = Ranking.create(user_id: params[:user_id], game_id: params[:game_id])
    @message = @ranking.new_rank(new_score: params[:new_score])
    flash[:notice] = @message
    redirect_to user_path(@ranking.user_id)
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    if request.env["omniauth.auth"]
      #binding.pry
      user = request.env["omniauth.auth"][:info][:name]
      if @user = User.find_by(name: user)
        session[:user_id] = @user.id
        redirect_to logged_in_home_path
      else
        @user = User.new(name: request.env["omniauth.auth"][:info][:name], password: SecureRandom.hex(8))
        @user.save
        render 'users/new_github'
      end
    else
      @user = User.find_by(name: params[:name])
        if @user && @user.authenticate(params[:password])
          session[:user_id] = @user.id
          redirect_to user_path(@user)
        else
          redirect_to signin_path
        end
      end
    end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def logged_in_home
    if current_user
      @user = current_user
    else
      render root_path
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to "/users/logged_in_home"
    else
      render 'users/new'
    end
  end

  def show
    if current_user
      @user = current_user
      @games = current_user.games
      respond_to do |f|
        f.html {render :show}
        f.json {render json: @user, status: 201}
      end
    else
      redirect_to root_path
    end
  end

  def update
    @user = User.find_by(name: user_params[:name])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      redirect_to root_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :console, :goal)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def home
    @user = current_user
     if logged_in
      redirect_to user_path(current_user)
       end 
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/helpers/ranking_helper.rb
module RankingHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/game/_form.html.erb
<%= form_for game do |f| %>

  <% if game.errors.any? %>

    <% game.errors.full_messages.each do |msg| %>
      <%= msg %>
  <% end %>

  What is the name of this game? 
  <%= f.label :name %>
  <%= f.text_field :name %></br>

  What kind of game is this?
  <%= f.label :game_type %>
  <%= f.text_field :game_type %></br>

  How many hours have you played?
  <%= f.label :play_time%>
  <%= f.number_field %></br>

  Who/what is your main character?
  <%= f.label :main_setup %>
  <%= f.text_field :main_setup %></br>

  what is your current skill rating?
  <%= f.label :score %>
  <%= f.number_field :score %>

  <%= f.submit "Click to submit!" %>
<% end %>

app/views/games/_form.html.erb
<%= form_for [@user, @game] do |f| %>
  <%= f.hidden_field :user_id, :value => @user.id %>

  <% if @game.errors.any? %>

    <% @game.errors.full_messages.each do |msg| %>
      <%= msg %>
    <% end %>
  <% end %>

  What is the name of this game?
  <%= f.text_field :name %></br>

  What kind of game is this?
  <%= f.text_field :game_type %></br>

  How many hours have you played?
  <%= f.number_field :play_time %></br>

  Who/what is your main character?
  <%= f.text_field :main_setup %></br>

  what is your current skill rating?
  <%= f.number_field :score %></br>

  <%= f.fields_for :rankings do |com| %>
  <%= com.hidden_field :user_id, :value => @user.id %>

  Leave a comment! : <%= com.text_field :comment %>
  <% end %>


  <%= f.submit "Click to submit!", :class => "js-newGame" %>
<% end %>

app/views/games/edit.html.erb
<h1> Let's edit <%= "#{@game.name}!" %> </h1>

<%= render 'form'%>
</br>
</br>

app/views/games/index.html.erb
<h4> Here is the full listing and rankings! </h4>

<div="js-AllGames" >
<% @games.each do |g| %>
  Game name: <%= link_to g.name, edit_user_game_path(current_user, g), class: "js-userGameEdit" %></br>
  Play time (hours): <%= g.play_time %></br>
  Setup: <%= g.main_setup %></br>
  Score: <%= g.score %></br>
  <%= link_to "Delete", user_game_path(current_user, g), method: :delete %> </br>
  <%= link_to " Details", user_game_path(current_user, g) %> </br></br>
<% end %>
</div>

app/views/games/new.html.erb
<h1> Please add a new game for us to track! </h1>

<%= render 'form' %>
</br>
</br>

app/views/games/score.html.erb
<% @score.each do |game| %>

  <%= game.name %>

<% end %>

app/views/games/show.html.erb
<% if Game.pro_level(@game.play_time) %>
  <%= @game.rank_symbol(@game.score) %>
  <% end %>

<h3>
  Game Type: <%= @game.game_type %> </br>
  Play Time: <%= @game.play_time %> </br>
  Main Setup: <%= @game.main_setup %> </br>
  Score: <%= @game.score %> </br>
  Last update at all: <%= @game.updated_at %> </br> </h3>
  <%= link_to "Delete", user_game_path(current_user, @game), method: :delete %> </br>

     <!-- Your Comments: <%#= @rank.comment %></br> </br> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsRankingProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag "application" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/user/new.html.erb
<h1> Thanks for signing up with us! </h1>

<%= form_for @user do |f| %>

  <% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |msg| %>
      <%= msg %>
  <% end %>

  Please pick a User Name
  <%= f.label :name %>
  <%= f.text_field :name %></br>

  Please enter your Email address
  <%= f.label :email %>
  <%= f.text_field :email %></br>

  What console do you play on?
  <%= f.label :console %>
  <%= f.text_field :console %></br>

  WHat is you desired skill rating?
  <%= f.label :goal %>
  <%= f.number_field :goal %></br>

  Please choose a password
  <%= f.label :password %>
  <%= f.password_field :password %></br> 

  <%= f.submit "Create Account!" %>
<% end %>

app/views/users/logged_in_home.html.erb
<h1 data-user-id="<%= @user.id %>"> Welcome back, <%= @user.name %> </h1>

<div class="nav">
  <%= link_to "Add a game", new_user_game_path(@user), :class => "js-addGame" %>
  <%= link_to "Log out", logout_path %>
  <%= link_to "Game List", user_games_path(@user), :class => "js-gameIndex" %>
</div>

<div class="ajaxForm">
</div>

<div class="js-indexShow">
  <ol><strong>
    <h3><div class="showHeading"></div><h3>
    <div class="gameName"> </div>
    <div class="gameType"> </div>
    <div class="gameTime"> </div>
    <div class="gameSetup"> </div>
    <div class="gameScore"> </div>
    <div class="gameComments"></div>

    <div class="js-userGameEdit"></div>
  </strong>
  </ol>
</div>

<script id="edit-game-template" type="text/x-handlebars-template">
  <form class="edit_game" id="edit_game_{{id}}" action="/users/{{user_id}}/games/{{id}}" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="&#x2713;" /><input type="hidden" name="_method" value="patch" />
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <input value="1" type="hidden" name="{{user_id}}" id="game_user_id" />

    What is the name of this game?
    <input type="text" value="{{name}}" name="game[name]" id="game_name" /></br>

    What kind of game is this?
    <input type="text" value="{{game_type}}" name="game[game_type]" id="game_game_type" /></br>

    How many hours have you played?
    <input type="number" value="{{play_time}}" name="game[play_time]" id="game_play_time" /></br>

    Who/what is your main character?
    <input type="text" value="{{main_setup}}" name="game[main_setup]" id="game_main_setup" /></br>

    what is your current skill rating?
    <input type="number" value="{{score}}" name="game[score]" id="game_score" />

    <input type="submit" name="commit" value="Click to submit!" class="js-submit" data-disable-with="Click to submit!" />
  </form>
</script>

<script id="games-template" type="text/x-handlebars-template">

    <li><strong> Game: {{name}}</strong></li>
    <li> Play Time(in hours): {{play_time}} </li>
    <a href="/users/{{user_id}}/games/{{id}}" id="showGame"> details...</a>,
    <a href="/users/{{user_id}}/games/{{id}}/edit" id="editGame">Edit {{name}}</a>,
    <a href="/users/{{user_id}}/games/{{id}}" id="fullViewGame">Full Specifics of {{name}}?</a>
</script>

<ul class="games_list" data-role="gameview" data-filter="true">
   <button class="gameSort">Sort by name!</button>
</ul>

<ul class="games_all" data-role="gameview" data-filter="true">
</ul>

app/views/users/new.html.erb
<h1> Thanks for signing up with us! </h1>

<%= form_for @user do |f| %>

  <% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |msg| %>
      <%= msg %></br>
    <% end %>
  <% end %>

  Please pick a User Name
  <%= f.text_field :name %></br>

  Please enter your Email address
  <%= f.text_field :email %></br>

  What console do you play on?
  <%= f.text_field :console %></br>

  What is you desired skill rating?
  <%= f.number_field :goal %></br>

  Please choose a password
  <%= f.password_field :password %></br>

  <%= f.submit "Create Account!" %>
<% end %>

app/views/users/new_github.html.erb
<%= form_for @user do |f| %>

<%= f.hidden_field :name %></br>

What console do you play on?
<%= f.text_field :console %></br>

What is you desired skill rating?
<%= f.number_field :goal %></br>

<%= f.submit %>
<% end %>

app/views/users/show.html.erb
<% if flash[:notice] %>
  <%= flash[:notice] %>
<% end %>
<%= link_to "main page", "/users/logged_in_home" %><br>
<h3> Your current stats: </h3>
<h5>Preferred console: <%= @user.console %> </br>
Current score goal: <%= @user.goal %> </br> </h5>

  <% @games.each do |g| %></br>
  <%= link_to g.name, edit_user_game_path(current_user, g), class: "js-userGameEdit" %></br>
  <%= link_to "Delete", user_game_path(@user, g), method: :delete %> </br>
  <%= g.score %></br>

  <% end %>
</div>

app/views/users/update.html.erb
<%= form_for @user do |f| %>

<%= f.hidden_field :name %></br>

What console do you play on?
<%= f.text_field :console %></br>

What is you desired skill rating?
<%= f.number_field :goal %></br>

<%= f.submit %>
<% end %>

app/views/welcome/home.html.erb
<div class = "welcome_title" >
<h1> Welcome to the Rankings Tracker </h1>
</div>
<div = "welcome_buttons" >
  <%= link_to "Sign up now!", new_user_path %>
  <%= link_to "Sign in now!", signin_path %>

  <%= link_to "Sign in with Github", "/auth/github" %>